### ISSUE TITLE
[1.2.1] Fetcher still crashes

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/LambdaLib#32]
env: IDEA dev environment

stacktrace:

```
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.net.ConnectException: Connection timed out: connect
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.Socket.connect(Socket.java:589)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:988)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:986)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.AccessController.doPrivileged(Native Method)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:985)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.AccessController.doPrivileged(Native Method)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.net.URL.openStream(URL.java:1038)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cn.lambdalib.util.version.Fetcher.run(CheckManger.java:126)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Thread.run(Thread.java:745)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cn.lambdalib.util.version.Fetcher.run(CheckManger.java:139)
[00:06:18] [Thread-10/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Thread.run(Thread.java:745)
```

**Comment by KSkun** [comment]
```
java.net.ConnectException: Connection timed out: connect
```

你确定这不是因为本地连GitHub太慢？

**Comment by WeAthFoLD** [comment]
@KSkun 就算如此，打印栈追踪也不是理想行为。按理说应该打印一条警告信息了事。

**Comment by ShieLian** [comment]
@WeAthFoLD 按理说是应该打印一条警告信息，但是这是一个IOException，异常情况过于多，需要详细信息诊断。

**Comment by KSkun** [comment]
@ShieLian 那应该试图筛掉一些正常的Exception并且只输出有用的信息，如`Connection timed out: connect`。打印栈刷log不是理想行为。用ConnectException#getMessage()来输出会不会好些呢？

**Comment by WeAthFoLD** [comment]
可以考虑用DEBUG flag来判断输出完整追踪还是输出警告信息

**Comment by KSkun** [comment]
就算是完整信息也未免太长了点，我还是主张只输出Exception的Message

**Comment by KSkun** [comment]
Close via 7d612cf
